description: A selection of BGCs producing GCF4
name: GCF4
pep_version: 2.1.0
rules:
  bigscape: false
  bigslice: false
  clinker: true
  interproscan: false
  mmseqs2: true
  query-bigslice: false
sample_table: samples.csv
