description: A selection of BGCs producing Trans_AT_network_raw
gtdb-tax: ../gtdbtk.bac120.summary.tsv
name: Trans_AT_network_raw
pep_version: 2.1.0
rules:
  bigscape: true
  bigslice: false
  clinker: false
  interproscan: false
  mmseqs2: false
  query-bigslice: false
sample_table: samples.csv
