description: A selection of BGCs producing GCF6
gtdb-tax: ../gtdbtk.bac120.summary.tsv
name: GCF6
pep_version: 2.1.0
rules:
  bigscape: false
  bigslice: false
  clinker: true
  interproscan: false
  mmseqs2: true
  query-bigslice: false
sample_table: samples_curated.csv
