description: A selection of BGCs producing largimiycin 38
name: largimiycin 38
pep_version: 2.1.0
rules:
  bigscape: false
  bigslice: false
  clinker: true
  interproscan: true
  mmseqs2: true
  query-bigslice: false
sample_table: samples.csv
