description: A selection of BGCs producing GCF7
name: GCF7
pep_version: 2.1.0
rules:
  bigscape: false
  bigslice: false
  clinker: true
  interproscan: false
  mmseqs2: true
  query-bigslice: false
sample_table: samples.csv
